name: Build Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t app -f ./MyApi/Dockerfile .

      - name: Get commit hash
        id: commit_hash
        run: echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Tag Docker image
        run: docker tag app your-dockerhub-username/app:${{ steps.commit_hash.outputs.hash }}

      - name: Push Docker image
        run: docker push your-dockerhub-username/app:${{ steps.commit_hash.outputs.hash }}
