name: Deploy to devel
on:
  workflow_run:
    workflows: ["Build Image"]
    types:
      - completed
jobs:
    build:
      runs-on: ubuntu-latest    
      steps:
      - name: echo
        run: echo