name: Build to ECR
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push platform-identity Docker image to Amazon ECR
        uses: docker/build-push-action@v3
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: default
          IMAGE_TAG: hello
        with:
          platforms: linux/amd64
          context: .
          file: ./MyApi/Dockerfile
          push: true
          tags: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:api-${{ env.IMAGE_TAG }}

      - name: Retag image
        uses: abronin/ecr-retag-action@v1
        env:
          ECR_REPOSITORY: default
          IMAGE_TAG: api-hello
        with:
            repository: ${{ env.ECR_REPOSITORY }}
            tag: ${{ env.IMAGE_TAG }}
            new-tags: hello, world