name: Manual deploy

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag for the Docker image'
        required: true
        default: ''
      environment:
        type: 'environment'
        description: 'Select the environment'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Verify Git tag
        run: |
          if ! git rev-parse -q --verify "${{ github.event.inputs.git_tag }}"; then
            echo "Invalid Git tag '${{ github.event.inputs.git_tag }}'"
            exit 1
          fi
      
      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/app:${{ github.event.inputs.git_tag }}
