name: Manual build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t app -f ./MyApi/Dockerfile .

      - name: Get commit hash
        id: commit_hash
        run: echo "hash=(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Tag Docker image
        run: docker tag app ${{ secrets.DOCKERHUB_USERNAME }}/app:app-${{ steps.commit_hash.outputs.hash }}

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/app:app-${{ steps.commit_hash.outputs.hash }}
     
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.commit_hash.outputs.hash }}',
              sha: context.sha
            })
            
      - name: Set tag in variable and print it
        id: set_tag
        run: echo "::set-output name=tag::${{ steps.create_tag.outputs.response.data.ref }}"    
        
    
