name: Release tag
on:
   push:
    branches:
    - 'main'
    - 'release/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        