name: Release tag
on:
   workflow_dispatch:
    inputs:
      git_tag:
        description: 'Git tag for a new release'
        required: true
        default: ''

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Fetch all
      run: |
         git fetch --all --tags

    - name: Check Tag exists
      uses: mukunku/tag-exists-action@v1.2.0
      id: checkTag
      with: 
        tag: '${{inputs.git_tag }}'

   

    - name: Exit if tag not found
      if: steps.checkTag.outputs.exists == 'false'
      run: exit 1

    - name: Extract release
      id: release
      run: |
         version="${{inputs.git_tag}}"

         echo "tag=$(echo $version | cut -d '-' -f 1)" >> $GITHUB_OUTPUT
         echo "hash=$( git rev-list -n 1 ${{inputs.git_tag}})" >> $GITHUB_OUTPUT
         echo "sha_short=$(git rev-parse --short $( git rev-list -n 1 ${{inputs.git_tag}}))" >> $GITHUB_OUTPUT


         
    - uses: rickstaa/action-create-tag@v1
      id: "tag_create"
      with:
        tag: "${{steps.release.outputs.tag}}"
        tag_exists_error: false
        commit_sha: ${{steps.release.outputs.hash}}



      
    # - name: Create release tag
    #   uses: actions/github-script@v6
    #   with:
    #     script: |
    #       github.rest.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: 'refs/tags/${{steps.release.outputs.tag}}',
    #         sha: '${{steps.release.outputs.hash}}'
    #       })
      
   
    # - name: Retag
    #   run: |
    #     git tag ${{steps.release.outputs.tag}} $(git rev-list -n 1 ${{steps.release.outputs.hash}})
    #     git push origin ${{steps.release.outputs.tag}}

    
    # - uses: rickstaa/action-create-tag@v1
    #   id: "tag_create"
    #   with:
    #     tag: "${{steps.release.outputs.tag}}"
    #     tag_exists_error: false
    #     commit_sha: ${{steps.release.outputs.hash}}


  

  
    # - name: Tag commit
    #   uses: actions/github-script@v5
    #   with:
    #     script: |
    #       github.rest.git.createRef({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         ref: 'refs/tags/23.05.${{github.run_number}}-20230101-PLAT-1244',
    #         sha: context.sha
    #       })

    # - name: Read Last tag
    #   id: read_last_tag
    #   run: |
    #       git fetch --all --tags
    #       echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT


    # - name: Retag
    #   run: |
    #     version="${{steps.read_last_tag.outputs.tag}}"
    #     release=$(echo $version | cut -d '-' -f 1)
    #     echo $release

    #     git tag $release $(git rev-list -n 1 ${{steps.read_last_tag.outputs.tag}})
    #     git push origin --tags
