name: Release tag
on:
   push:
    branches:
    - 'main'
    - 'release/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Echo tag
      run: echo ${{github.run_number}}
    
    - name: Tag commit
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/${{github.run_number}}',
            sha: context.sha
          })

    - name: Fetch all
      run: |
        git fetch --all --tags


    - name: Retag
      run: |
        git tag x${{github.run_number}} $(git rev-list -n 1 ${{github.run_number}})
        git push