name: Release tag
on:
   push:
    branches:
    - 'main'
    - 'release/**'


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Echo tag
      run: echo ${{github.run_number}}
    
    - name: Tag commit
      uses: actions/github-script@v5
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: 'refs/tags/23.05.${{github.run_number}}-20230101-PLAT-1244',
            sha: context.sha
          })

    - name: Read Last tag
      id: read_last_tag
      run: |
          git fetch
          echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT


    - name: Retag
      run: |
        version="${{steps.read_last_tag.outputs.tag}}"
        release=$("${version}" | cut -d '-' -f 1)

        git tag x${{github.run_number}} $(git rev-list -n 1 ${{github.run_number}})
        git push origin --tags
