name: New Release Workflow
on:
  workflow_dispatch:
  push:
    branches:
    - 'main'
    - 'release/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: echo
      run: echo 123
