name: Build Image
on:
  # push:
  #   branches:
  #   - 'main'
  #   - 'release/**'

  pull_request:
    types:
      - closed
    branches:
    - 'main'
    - 'release/**'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0     

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0
      with:
        useConfigFile: true

    - name: Extract PLAT-<1..7 digits>
      id: jira
      run: |
          extracted_value=$(echo "${{ github.event.pull_request.head.ref }}" | grep -o -E 'PLAT-\d{1,7}')
          if [[ -n $extracted_value ]]; then
            echo "::set-output name=plat::$extracted_value"
          else
            echo "::set-output name=plat::FALLBACK_VALUE"
          fi
          
    - name: Create tag
      uses: actions/github-script@v5
      with:
        script: |
              github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ steps.jira.outputs.plat }}',
                sha: context.sha
              })
